@startuml 
(script) -> (dataset)
(script) --> (sqlTemplate)
(script) -> (quality-metric)
(schedule) --> (scenarioActs[]): cascade
(scenarioActs[]) --> (scenarioAct): cascade
(scenarioActTemplate) ------> (scenarioAct)
'(scenarioActTemplate) -> (task)
(scenarioAct) --> (task): cascade
(taskExecutionService)------->(task)
(dataset) --> (scenarioAct)
(dataset) -->(quality-metric)
(dataSource) --> (dataset)
(nameSpace) -----> (dataset)
(nameSpace) .> (schedule)
(driver)-->(dataSource)
(sqlTemplate) --> (driver)
(sqlTemplate) --> (dataSource)
(sqlTemplate) --> (dataset)
(catalog) o..o  (dataSource)
(nameSpace) .> (dataSource)
@enduml 