@startuml 
(schedule) --> (scenarioActs[])
(scenarioActs[]) --> (scenarioAct)
(scenarioActTemplate) -> (scenarioAct)
(scenarioActTemplate) -> (task)
(scenarioAct) --> (task)
(task)-->(taskExecutionService)
(dataset) -> (scenarioAct)
(dataSource) --> (dataset)
(project) -> (dataset)
(project) ..> (schedule)
(driver)-->(dataSource)
(sqlTemplate) --> (driver)
(sqlTemplate) --> (dataSource)
(sqlTemplate) --> (dataset)
(catalog) o--o  (dataSource)
(project) .> (dataSource)
@enduml 