server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresDB?ApplicationName=stateSVC
    username: postgresUser
    password: postgresPW
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://lakehouse-auth-svc:8080/realms/lakehouse}
      client:
        registration:
          keycloak-internal:
            provider: keycloak
            client-id: lakehouse-internal-client
            client-secret: ${KEYCLOAK_INTERNAL_CLIENT_SECRET:super-secret-internal-key-987654321}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_ISSUER_URI:http://lakehouse-auth-svc:8080/realms/lakehouse}/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_ISSUER_URI:http://lakehouse-auth-svc:8080/realms/lakehouse}/protocol/openid-connect/token
  jpa:
    generate-ddl: true
    ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      transaction:
        jta:
          platform: org.hibernate.service.jta.platform.internal.JBossStandAloneJtaPlatform
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        default_schema: lakehouse_state

lakehouse:
  health:
    liveness-path: /healthz
    readiness-path: /readyz
