apiVersion: v1
kind: ServiceAccount
metadata:
  name: lakehouse-app-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lakehouse-app-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications", "scheduledsparkapplications", "sparkconnects"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps", "events"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lakehouse-app-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: lakehouse-app-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: lakehouse-app-role
  apiGroup: rbac.authorization.k8s.io
