<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
    </parent>
    <groupId>lakehouse</groupId>
    <artifactId>lakehouse-parent</artifactId>
    <version>0.8.0</version>
    <packaging>pom</packaging>
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <modules>
        <module>lakehouse-common</module>
        <module>lakehouse-config-svc</module>
        <module>lakehouse-config-rest-client</module>
        <module>lakehouse-scheduler-rest-client</module>
        <module>lakehouse-scheduler-svc</module>
        <module>lakehouse-state-rest-client</module>
        <module>lakehouse-task-executor-svc</module>
        <module>lakehouse-ui-svc</module>
        <module>lakehouse-cli</module>
        <module>lakehouse-common-test</module>
        <module>lakehouse-common-rest-client</module>
        <module>lakehouse-common-health</module>
        <module>lakehouse-state-svc</module>
        <module>lakehouse-jinjava</module>
        <module>lakehouse-task-executor-rest-client</module>
        <module>lakehouse-spark-rest-client</module>
        <module>lakehouse-task-executor-api</module>
        <module>lakehouse-validators</module>
        <module>lakehouse-task-executor-spark-api</module>
        <module>lakehouse-task-executor-spark-dataset-app</module>
        <module>lakehouse-task-executor-spark-dq-app</module>
        <module>lakehouse-task-proxy-for-spark</module>
        <module>lakehouse-task-proxy-for-spark-api</module>
        <module>lakehouse-task-proxy-for-spark-rest-client</module>
    </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>1.20.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>17</java.version>
        <junit-jupiter.version>6.1.3</junit-jupiter.version>
        <springdoc.version>3.1.0</springdoc.version>
        <kafka.testcontainers.version>1.19.3</kafka.testcontainers.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>

<!--
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
-->

    </dependencies>
</project>
