conf-svc:
  image:
    repository: lakehouse
    tag: "0.10.0"
    pullPolicy: IfNotPresent

keycloak:
  issuerUri: "http://keycloak:8085/realms/lakehouse"
  internalClientSecret: "super-secret-internal-key-987654321"
