@startuml
skinparam StateFontName Arial
skinparam StateFontSize 12
skinparam StateBackgroundColor #FEFECE
skinparam StateBorderColor #A2A2A2

title SparkApplication Lifecycle (K8s Operator)

[*] --> UNKNOWN : Resource creation in K8s

state UNKNOWN {
}

UNKNOWN --> SUBMITTED : Operator accepted the task

state SUBMITTED {
}

SUBMITTED --> RUNNING : Task started\n[runningLatch.countDown()]

state RUNNING {
}


UNKNOWN --> TIMEOUT : startupTimeout exceeded\n[runningLatch timeout]
SUBMITTED --> TIMEOUT : startupTimeout exceeded\n[runningLatch timeout]
RUNNING --> TIMEOUT : businessTimeout exceeded\n[terminalLatch timeout]

state TIMEOUT #ffcccc {
  TIMEOUT : TaskFailedException is thrown
  TIMEOUT : Resource is NOT deleted automatically
}


RUNNING --> COMPLETED : Successful completion\n[terminalLatch.countDown()]

state COMPLETED #ccffcc {
  COMPLETED : logDelivery() logic is called
  COMPLETED : Resource auto-cleanup triggers (delete)
}

RUNNING --> FAILED : Execution error\n[terminalLatch.countDown()]
SUBMITTED --> FAILED : Bypassing RUNNING\n[running + terminal Latch.countDown()]

state FAILED #ffcccc {
  FAILED : logDelivery() logic is called
  FAILED : TaskFailedException is thrown
  FAILED : Resource is NOT deleted for debugging
}

COMPLETED --> [*] : Successful exit
FAILED --> [*] : Exit with error
TIMEOUT --> [*] : Exit by timeout

@enduml
