@startuml
!pragma layout smetana
':ui-svc: as uisvc
:config-svc:  as confsvc
:status-svc:  as statussvc
:task-executor-svc:  as taskexecutorsvc
:scheduler-svc: as schedulersvc
:cvs-svc: as cvssvc
':cmd-cli: as cmdcli
cvssvc ---> confsvc
schedulersvc -> confsvc
'uisvc --> confsvc
'uisvc ---> schedulersvc
'cmdcli --> confsvc
'cmdcli --> schedulersvc
schedulersvc <-- taskexecutorsvc
taskexecutorsvc --> statussvc
taskexecutorsvc --> confsvc
taskexecutorsvc --->(sparkexecutors):task-executorsvc may be a spark  driver
@enduml