@startuml
autonumber

"cvs-svc" -> "conf-svc" : all configs
queue broker as broker
"conf-svc" --> broker : schedule confugurations
broker -> "scheduler-svc" : schedule confugurations
"scheduler-svc" -> broker : queued task
broker -> "task-executor-svc" : queued task
"task-executor-svc" -> "scheduler-svc" : request lock queued task
"scheduler-svc" -> "conf-svc" : request task details
"scheduler-svc" -> "task-executor-svc" : response lock with task details or error
"task-executor-svc" -> "scheduler-svc" : send task lock heardbeat
"task-executor-svc" -> "scheduler-svc" : send release lock
@enduml