@startuml
autonumber

"cvs-svc" -> "conf-svc" : all configs
queue schedule_changes
queue scheduled_task_msg
"conf-svc" -> schedule_changes : schedule configurations ScheduleEffectiveDTO
schedule_changes -> "scheduler-svc" : consume ScheduleEffectiveDTO

"scheduler-svc" -> scheduled_task_msg : send ScheduledTaskMsgDTO
scheduled_task_msg -> "task-executor-svc" : respond ScheduledTaskMsgDTO
"task-executor-svc" -> "scheduler-svc" : lockTaskById ScheduledTaskMsgDTO.id
"scheduler-svc" -> "conf-svc" : request task details TaskDTO scheduledTaskEffectiveDTO
"scheduler-svc" -> "task-executor-svc" : response ScheduledTaskLockDTO with task details or error
"task-executor-svc" -> "scheduler-svc" : send TaskExecutionHeartBeatDTO
"task-executor-svc" -> "scheduler-svc" : send TaskInstanceReleaseDTO to release lock
"cli" <- "scheduler-svc" : get tasks info ScheduledTaskDTO
@enduml