@startuml
'https://plantuml.com/sequence-diagram

autonumber

"task-executor-svc" -> "state-svc": send DataSetStateDTO
"task-executor-svc" -> "state-svc": request for dependency states. Body - DataSetIntervalDTO
"state-svc" --> "task-executor-svc" : response dependencies. Body DataSetStateResponseDTO

@enduml