@startuml
'https://plantuml.com/sequence-diagram



"task-executor-svc" -> "state-svc": 1.send DataSetStateDTO
"task-executor-svc" --> "state-svc": 1.request for dependency states. Body - DataSetIntervalDTO
"state-svc" --> "task-executor-svc" : 2.response dependencies. Body DataSetStateResponseDTO

@enduml