@startuml
'https://plantuml.com/use-case-diagram
!pragma layout smetana

database datawarehouses
database sources

de ---->   [config]
[config] --> (lakehouse-app)

(lakehouse-app) --> sources
(lakehouse-app) --> datawarehouses: refreshData
(lakehouse-app) --> datawarehouses: DataQuality
(lakehouse-app) --> sources: DataQuality



datawarehouses --> (bi)
sources -> datawarehouses

dataUser ---> (lakehouse-app):what's my data
dataUser ---> datawarehouses:where i see it
dataUser ---> bi:where i see it

@enduml