apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-history-conf
data:
  spark-defaults.conf: |
    spark.eventLog.enabled=true
    spark.eventLog.dir=s3a://sparklogs/eventlog/  
    # sparkhistory
    spark.history.fs.logDirectory=s3a://sparklogs/eventlog/
    spark.history.ui.port=18080
    # all
    spark.hadoop.fs.s3a.path.style.access=true
    spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.endpoint=http://minio:9000
    spark.driver.extraJavaOptions=-Dlog4j2.configurationFile=file:///opt/spark/conf/log4j2.properties
    spark.executor.extraJavaOptions=-Dlog4j2.configurationFile=file:///opt/spark/conf/log4j2.properties
    

