apiVersion: v1
kind: Service
metadata:
  name: lakehouse-task-executor-svc
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app.kubernetes.io/name: lakehouse-task-executor-svc
    app.kubernetes.io/instance: {{ .Release.Name }}
