apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hive-metastore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hive-metastore.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: alpine:3.18
          command:
            - sh
            - -c
            - |
              # ИСПРАВЛЕНО: Чистый синтаксис nc, работающий в Alpine
              echo "Waiting for PostgreSQL to be ready..."
              until nc -z db-dev 5432; do
                echo "Postgres is unavailable - sleeping"
                sleep 2
              done
              echo "PostgreSQL is up and running!"
        - name: wait-and-init-minio
          image: lakehouse-s3-check:0.5.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_ENDPOINT
              value: "http://minio:9000"
            - name: MINIO_ROOT_USER
              value: "spark_user"
            - name: MINIO_ROOT_PASSWORD
              value: "spark_pwd"
      containers:
        - name: hive-metastore
          image: "{{ .Values.config.image.repository }}:{{ .Values.config.image.tag }}"
          imagePullPolicy: {{ .Values.config.image.pullPolicy }}

          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Checking Metastore schema status..."
              if /opt/hive/bin/schematool -dbType {{ .Values.config.hiveConfig.databaseType }} -info; then
                  echo "Schema already exists and is valid. Proceeding to start..."
              else
                  echo "Schema not found or uninitialized. Initializing clean database..."
                  /opt/hive/bin/schematool -dbType {{ .Values.config.hiveConfig.databaseType }} -initSchema
                  echo "Schema initialized successfully."
              fi
              echo "Starting Hive Metastore Server..."
              exec /opt/hive/bin/hive --service metastore

          env:
            - name: HADOOP_CLASSPATH
              value: "{{ .Values.config.hiveConfig.env.HADOOP_CLASSPATH }}:/opt/hive/lib/postgresql-42.7.3.jar"
            - name: DATABASE_TYPE
              value: "{{ .Values.config.hiveConfig.databaseType }}"
            - name: HIVE_CONF_DIR
              value: /opt/hive/conf
            - name: HADOOP_CONF_DIR
              value: /opt/hive/conf

          volumeMounts:
            - name: hive-config
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: metastore-site.xml
      volumes:
        - name: hive-config
          configMap:
            name: {{ include "hive-metastore.fullname" . }}-config

