apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    app.kubernetes.io/name: hive-metastore
spec:
  type: ClusterIP
  ports:
    - port: 9083
      targetPort: 9083
      protocol: TCP
      name: thrift
  selector:
    app.kubernetes.io/name: hive-metastore
