apiVersion: v2
name: lakehouse-management
description: Umbrella chart.
type: application
version: 0.1.0
appVersion: "0.11.0"
dependencies:
  - name: lakehouse-config-svc
    version: "0.1.0"
    repository: "file://../lakehouse-config-svc"
  - name: lakehouse-scheduler-svc
    version: "0.1.0"
    repository: "file://../lakehouse-scheduler-svc"
  - name: lakehouse-state-svc
    version: "0.1.0"
    repository: "file://../lakehouse-state-svc"
  - name: lakehouse-task-executor-service
    version: "0.1.0"
    repository: "file://../lakehouse-task-executor-svc"
  - name: hive-metastore
    version: 0.1.0
    repository: "file://../hive-metastore"
  - name: trino
    version: 1.0.0
    repository: "file://../trino"
    condition: trino.enabled
  - name: spark-history
    version: 0.1.0
    repository: "file://../spark-history"
  - name: lakehouse-task-proxy4spark
    version: 0.1.0
    repository: "file://../lakehouse-task-proxy4spark"
  - name: lakehouse-ui-svc
    version: 0.1.0
    repository: "file://../lakehouse-ui-svc"
  - name: git-server
    version: 0.1.0
    repository: "file://../git-server"
  - name: lakehouse-ui-modeller-svc
    version: 0.1.0
    repository: "file://../lakehouse-ui-modeller-svc"

