apiVersion: v1
kind: Service
metadata:
  name: lakehouse-ui-svc
spec:
  type: {{ index .Values "ui-svc" "service" "type" }}
  ports:
    - port: {{ index .Values "ui-svc" "service" "port" }}
      targetPort: {{ index .Values "ui-svc" "service" "targetPort" }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: lakehouse-ui-svc
    app.kubernetes.io/instance: {{ .Release.Name }}