@startuml
'https://plantuml.com/sequence-diagram

"task-executor-svc" -> "state-svc": 1.set state LOCKED DataSetStateDTO
"task-executor-svc" -> "state-svc": 2.request wrong states. Body DataSetIntervalDTO
"state-svc" --> "task-executor-svc" : 3.response wrong states. Body DataSetWrongStateResponseDTO
"task-executor-svc" -> "state-svc": 4.set state SUCCESS DataSetStateDTO
@enduml