apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-dev-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # Фиксированный размер диска 2 Гигабайта
