apiVersion: v1
kind: Service
metadata:
  name: openbao
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lakehouse-management.labels" . | nindent 4 }}
    app.kubernetes.io/component: openbao
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
  selector:
    {{- include "lakehouse-management.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: openbao