apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-seed-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openbao-seed-tokenreview
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openbao-seed-tokenreview-{{ .Release.Name }}-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: openbao-seed-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: openbao-seed-tokenreview
  apiGroup: rbac.authorization.k8s.io
