@startuml
'https://plantuml.com/sequence-diagram
[* generateSource\n @daily] -> (transaction_processing)
[* generateSourceDict\n @daily] -> (client_processing)
[* regular\n @daily]-> (transaction_dds)
(client_processing) --->  (transaction_dds)
(transaction_processing) --> (transaction_dds)
(transaction_dds) -> (aggregation_pay_per_client_daily_mart)
(transaction_dds) -> (aggregation_pay_per_client_total_mart)
@enduml