apiVersion: v1
kind: ConfigMap
metadata:
  name: git-server-config
  labels:
    {{- include "git-server.labels" . | nindent 4 }}
data:
{{- $root := . }}
{{- range $path, $_ := .Files.Glob "conf/**" }}
  {{- $rel := trimPrefix "conf/" $path }}
  {{- $key := replace "/" "." $rel }}
  {{ $key }}: |-
{{ $root.Files.Get $path | indent 4 }}
{{- end }}
