apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-server-storage
  labels:
    {{- include "git-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{  (index .Values "git-server").persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{  (index .Values "git-server").persistence.size | default "1Gi" }}
