apiVersion: v1
kind: Service
metadata:
  name: git-server
  labels:
    {{- include "git-server.labels" . | nindent 4 }}
spec:
  type: {{  (index .Values "git-server").service.type | default "ClusterIP" }}
  ports:
    - port: {{  (index .Values "git-server").service.port | default 9418 }}
      targetPort: {{  (index .Values "git-server").service.targetPort | default 9418 }}
      protocol: TCP
  selector:
    {{- include "git-server.selectorLabels" . | nindent 4 }}
