version: '3.9'

services:

  db:
    image: postgres
    container_name: db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPW
      POSTGRES_DB: postgresDB
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 100
  #docker run -d -p 9083:9083 --env SERVICE_NAME=metastore --name metastore-standalone apache/hive:${HIVE_VERSION}

#  hms:
#    image: apache/hive:3.1.3
#    container_name: hms
#    ports:
#      - "9083:9083"
#    environment:
#      SERVICE_NAME: metastore


  #minio:
  #  image: minio/minio
  #  ports:
  #    - "9000:9000"
  #    - "9001:9001"
  #  volumes:
  #    - minio_storage:/data
  #  environment:
  #    MINIO_ROOT_USER: masoud
  #    MINIO_ROOT_PASSWORD: Strong#Pass#2022
  #  command: server --console-address ":9001" /data

  conf-svc:
    image: lakehouse
    container_name: conf-svc
#    restart: always
    ports:
      - "8080:8080"
    command: >
      bash -c "java
      -Dspring.datasource.url=jdbc:postgresql://db:5432/postgresDB
      -Dlakehouse.config.schedule.kafka.producer.bootstrap-servers=broker:9092
      -jar /opt/lakehouse-config-svc/lakehouse-config-svc-0.0.1-jar-with-dependencies.jar"
    depends_on:
#      - minio
      - db
      - broker
#      - hms
  scheduler-svc:
    image: lakehouse
    container_name: scheduler-svc
#    restart: always
    ports:
      - "8081:8081"
    command: >
      bash -c "java
      -Dspring.datasource.url=jdbc:postgresql://db:5432/postgresDB 
      -Dlakehouse.scheduler.schedule.task.kafka.producer.properties.bootstrap.servers=broker:9092 
      -Dlakehouse.scheduler.config.schedule.kafka.consumer.properties.bootstrap.servers=broker:9092 
      -Dlakehouse.scheduler.registration.delay-ms=5000 
      -Dlakehouse.scheduler.run.delay-ms=5000 
      -Dlakehouse.scheduler.resolvedeps.delay-ms=5000 
      -Dlakehouse.client.rest.config.server.url=http://conf-svc:8080 
      -jar /opt/lakehouse-scheduler-svc/lakehouse-scheduler-svc-0.0.1-jar-with-dependencies.jar"
    depends_on:
      - db
      - broker
      - conf-svc

  lakehouse-task-executor-svc-1:
    image: lakehouse
    container_name: task-executor-svc-1
    hostname: task-executor-svc-1
  #  restart: always
    ports:
      - "8082:8082"
      - "4040:4040"
    environment:
      SPARK_DRIVER_HOST: task-executor-svc-1
      SPARK_MASTER_HOST: task-executor-svc-1
    command: >
      bash -c "java
      --add-exports java.base/sun.nio.ch=ALL-UNNAMED 
      --add-opens=java.base/java.nio=ALL-UNNAMED 
      -Dserver.port=8082
      -Dlakehouse.client.rest.config.server.url=http://conf-svc:8080
      -Dlakehouse.client.rest.scheduler.server.url=http://scheduler-svc:8081
      -Dlakehouse.task-executor.service.groupName=default
      -Dlakehouse.task-executor.service.id=first1
      -Dlakehouse.task-executor.scheduled.task.kafka.consumer.concurrency=1
      -Dlakehouse.task-executor.scheduled.task.kafka.consumer.properties.bootstrap.servers=broker:9092
      -jar /opt/lakehouse-task-executor-svc/lakehouse-task-executor-svc-0.0.1-jar-with-dependencies.jar"
    depends_on:
#     - minio
      - broker
      - conf-svc
      - scheduler-svc

  lakehouse-task-executor-svc-2:
    image: lakehouse
    container_name: task-executor-svc-2
    hostname: task-executor-svc-2
    #  restart: always
    ports:
      - "8083:8083"
      - "4042:4042"
    environment:
      SPARK_DRIVER_HOST: task-executor-svc-2
      SPARK_MASTER_HOST: task-executor-svc-2
    command: >
      bash -c "java
      --add-exports java.base/sun.nio.ch=ALL-UNNAMED 
      --add-opens=java.base/java.nio=ALL-UNNAMED 
      -Dserver.port=8083
      -Dlakehouse.client.rest.config.server.url=http://conf-svc:8080
      -Dlakehouse.client.rest.scheduler.server.url=http://scheduler-svc:8081
      -Dlakehouse.task-executor.service.groupName=default
      -Dlakehouse.task-executor.service.id=second
      -Dlakehouse.task-executor.scheduled.task.kafka.consumer.concurrency=1
      -Dlakehouse.task-executor.scheduled.task.kafka.consumer.properties.bootstrap.servers=broker:9092
      -jar /opt/lakehouse-task-executor-svc/lakehouse-task-executor-svc-0.0.1-jar-with-dependencies.jar"
    depends_on:
#      - minio
      - broker
      - conf-svc
      - scheduler-svc

volumes:
  minio_storage: {}
