config:
  db:
    host: "db-dev"
    port: 5432
    name: "postgresDB"
    user: "postgresUser"
    password: "postgresPW"
  s3:
    endpoint: "http://minio:9000"
    accessKey: "spark_user"
    secretKey: "spark_pwd"
    warehouseDir: "s3a://data/warehouse"
    pathStyleAccess: "true"
  image:
    repository: lakehouse-hms
    tag: "0.4.0"
    pullPolicy: IfNotPresent
  hiveConfig:
    databaseType: "postgres"
    env:
      HADOOP_CLASSPATH: "/opt/hive/lib/postgresql-42.7.3.jar:/opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.1.0.jar:/opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.271.jar"

