apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
        - name: trino
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            # Раскладываем /etc/trino
            - name: etc-vol
              mountPath: /etc/trino/config.properties
              subPath: config.properties
            - name: etc-vol
              mountPath: /etc/trino/jvm.config
              subPath: jvm.config
            - name: etc-vol
              mountPath: /etc/trino/node.properties
              subPath: node.properties
            - name: etc-vol
              mountPath: /etc/trino/kafka/metric_status.json
              subPath: metric_status.json

            # Раскладываем каталоги
            - name: catalog-vol
              mountPath: /etc/trino/catalog/kafka.properties
              subPath: kafka.properties
            - name: catalog-vol
              mountPath: /etc/trino/catalog/lakehouse.properties
              subPath: lakehouse.properties
      volumes:
        - name: etc-vol
          configMap:
            name: {{ .Release.Name }}-trino-etc
        - name: catalog-vol
          configMap:
            name: {{ .Release.Name }}-trino-catalog
