@startuml 
(script) -> (dataset)
(script) --> (sqlTemplate)
(script) -> (quality-metric)
(scenarioActTemplate) ----> (schedule)
'(scenarioActTemplate) -> (task)
(taskExecutionService)--->(scenarioActTemplate)
(dataset) --> (schedule)
(dataset) -->(quality-metric)
(dataSource) --> (dataset)
(nameSpace) -----> (dataset)
(nameSpace) .> (schedule)
(driver)-->(dataSource)
(sqlTemplate) --> (driver)
(sqlTemplate) --> (dataSource)
(sqlTemplate) --> (dataset)
(catalog) o..o  (dataSource)
(nameSpace) .> (dataSource)
@enduml 