server:
  port: 8082

lakehouse:
  client:
    rest:
      scheduler:
        server:
          url: http://127.0.0.1:8081
  task-executor:
    service:
      groupName: default
      id: first
    scheduled:
      task:
        kafka:
          consumer:
            concurrency: 1
            properties:
              bootstrap.servers: localhost:9092
              group.id: task-executor
              auto.offset.reset: earliest
            topics: scheduled_task_msg
    schedule:
      lockTask:
        delay-ms: 1000
        initial-delay-ms: 1000
      heardBeatTask:
        delay-ms: 1000
        initial-delay-ms: 1000