@startuml
interface DataSourceManipulator
class SparkSession
class TrinoIcebergSparkDataSourceManipulator extends TrinoSparkDataSourceManipulatorAbstract
class TrinoSparkDataSourceManipulatorAbstract extends JdbcSparkDataSourceManipulatorAbstract
abstract class JdbcSparkDataSourceManipulatorAbstract extends SparkDataSourceManipulatorAbstract
abstract class SparkDataSourceManipulatorAbstract implements DataSourceManipulator{
SparkSession sparkSession,
            DataSourceDTO dataSourceDTO,
            JdbcUtils jdbcUtils,
            DataSetDTO dataSetDTO
}

SparkDataSourceManipulatorAbstract *- SparkSession
SparkDataSourceManipulatorAbstract *- DataSourceDTO
SparkDataSourceManipulatorAbstract *- JdbcUtils
SparkDataSourceManipulatorAbstract *- dataSetDTO

class PostgresJdbcSparkDataSourceManipulator extends JdbcSparkDataSourceManipulatorAbstract
class IcebergSparkDataSourceManipulator extends FileSparkDataSourceManipulatorAbstract
abstract class FileSparkDataSourceManipulatorAbstract extends SparkDataSourceManipulatorAbstract
class ParquetSparkDataSourceManipulator extends FileSparkDataSourceManipulatorAbstract
@enduml